rule "Primo VE Display - Date Of Publication 100 08 = a"
//ressource continue en cours Publié depuis Date1 
priority 10
	when
		MARC.data is "100"
        AND MARC."100"."a" match "^.{8}a.*"
	then
	    set TEMP"1" to MARC.data."100".Date1
		set pnx."display"."creationdate" to TEMP"1"
end

rule "Primo VE Display - Date Of Publication 100 08 = b"
//ressource continue en cours Publié depuis Date1 
priority 10
	when
		MARC.data is "100"
        AND MARC."100"."a" match "^.{8}b.*"
	then
	    set TEMP"1" to MARC.data."100".Date1
        replace spaces (TEMP"1","X")
        add prefix (TEMP"1","Depuis ")
        set TEMP"2" to MARC.data."100".Date2
        replace spaces (TEMP"2","X")
        add prefix (TEMP"2","jusqu'à ")
        concatenate with delimiter support empty vals (TEMP"1",TEMP"2"," ")

		set pnx."display"."creationdate" to TEMP"1"
end
// rule "Primo VE Display - Date Of Publication 210 d"
// priority 20
// 	when
// 		MARC."210"."d" does not equal "s.d"
// 	then
// 	    set TEMP"1" to MARC."210"."d"
// 	    remove substring using regex (TEMP"1","^\\[+")
// 	    remove substring using regex (TEMP"1","(]|:|,|=|/|\\.)+$")
// 		set pnx."display"."creationdate" to TEMP"1"
// end

// rule "Primo VE Display - Date Of Publication 210 h"
// priority 30
// 	when
// 		MARC."210"."h" does not equal "s.d"
// 		MARC."210" has any "h"
// 	then
// 	    set TEMP"1" to MARC."210"."h"
// 	    remove substring using regex (TEMP"1","^\\[+")
// 	    remove substring using regex (TEMP"1","(]|:|,|=|/|\\.)+$")
// 		set pnx."display"."creationdate" to TEMP"1"
// end


// rule "Primo VE Display - Date Of Publication 207 a"
// priority 40
// 	when
// 		MARC is "207"."a"
// 	then
// 	    set TEMP"1" to MARC."207"."a"
// 	    remove substring using regex (TEMP"1","^\\[+")
// 	    remove substring using regex (TEMP"1","(]|:|,|=|/|\\.)+$")
// 		set pnx."display"."creationdate" to TEMP"1"
// end